#!/bin/bash
if [ "$PROJECT_ENV_VARS_SET" == "" ]; then
  if [ "$SCRIPTS_PATH" == "" ]; then
    SCRIPTS_PATH=`dirname $0`
  fi
  set -o allexport
  SCRIPTS_PATH=`realpath "$SCRIPTS_PATH"`
  PROJECT_PATH=`realpath "$SCRIPTS_PATH/.."`
  source $PROJECT_PATH/.env
  set +o allexport

  PROJECT_TEXT_RESET="\e[0m"
  PROJECT_TEXT_RED="\e[31m"
  PROJECT_TEXT_GREEN="\e[32m"
  PROJECT_TEXT_YELLOW="\e[33m"
  PROJECT_TEXT_BOLD="\e[1m"
  PROJECT_STATUS_OK="$PROJECT_TEXT_GREEN$PROJECT_TEXT_BOLD[OK]$PROJECT_TEXT_RESET"
  PROJECT_STATUS_ERROR="$PROJECT_TEXT_RED$PROJECT_TEXT_BOLD[ERROR]$PROJECT_TEXT_RESET"
  PROJECT_STATUS_WARNING="$PROJECT_TEXT_YELLOW$PROJECT_TEXT_BOLD[WARNING]$PROJECT_TEXT_RESET"

  PROJECT_ENV_VARS_SET=1
fi
